[functions]

  [functions.emails]
  included_files = [
    "./emails/**"
  ]

[build]
publish = "."

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[context]

  [context.production]

    [context.production.functions]

      [context.production.functions.emails]
      included_files = [
        "./emails/**"
      ]

  [context.master]

    [context.master.functions]

      [context.master.functions.emails]
      included_files = [
        "./emails/**"
      ]